// This file was autogenerated by `create-eas-build-function` command.
// Go to README.md to learn more about how to write your own custom build functions.

function myFunction(ctx, { inputs, outputs, env }) {
  ctx.logger.info('Hello from my JavaScript function!');
}

export default myFunction;
