rules:
  - patterns: ['**/*']
    mentions: ['szdziedzic', 'khamilowicz', 'sjchmiela']
  - patterns: ['packages/eas-cli/src/build/**']
    mentions: ['szdziedzic', 'khamilowicz', 'sjchmiela']
  - patterns: ['packages/eas-cli/src/commands/build/**']
    mentions: ['szdziedzic', 'khamilowicz', 'sjchmiela']
  - patterns: ['packages/eas-cli/src/submit/**']
    mentions: ['szdziedzic', 'khamilowicz', 'sjchmiela']
  - patterns: ['packages/eas-cli/src/commands/submit.ts']
    mentions: ['szdziedzic', 'khamilowicz', 'sjchmiela']
  - patterns: ['packages/eas-cli/src/update/**']
    mentions: ['EvanBacon', 'byCedric', 'wschurman']
  - patterns: ['packages/eas-cli/src/commands/update/**']
    mentions: ['EvanBacon', 'byCedric', 'wschurman']
  - patterns: ['packages/eas-cli/schema/**']
    mentions: ['bycedric']
  - patterns: ['packages/eas-cli/src/metadata/**']
    mentions: ['bycedric']
  - patterns: ['packages/eas-cli/src/commands/metadata/**']
    mentions: ['bycedric']
  - patterns: ['packages/eas-json/**']
    mentions: ['szdziedzic', 'khamilowicz', 'sjchmiela']
