defaultSemverRangePrefix: ''
nodeLinker: node-modules

npmMinimalAgeGate: 2d

npmPreapprovedPackages:
  - '@expo/*'
  - 'eslint-plugin-universe'
  - 'oxlint-config-universe'
  - 'sandbox-cli-detector'
