coverage:
  round: up
  precision: 2
  range: 30..100
  status:
    patch: false
    project:
      default:
        informational: true
      eas-cli:
        informational: true
        paths:
          - packages/eas-cli
      eas-json:
        informational: true
        paths:
          - packages/eas-json
