name: Build Worker (iOS)

on:
  workflow_dispatch:
    inputs:
      upload_url:
        description: "Signed GCS upload URL for the worker tarball"
        type: string
        required: true

jobs:
  build_ios_worker:
    name: Build iOS Worker Tarball
    runs_on: macos-medium
    image: latest
    steps:
      - uses: eas/checkout

      - uses: eas/install_node_modules

      - name: Build worker tarball
        run: ./package.sh worker-ios.tar.gz ios

      - name: Upload worker tarball to GCS
        run: |
          curl -X PUT \
            -H "Content-Type: application/gzip" \
            --upload-file worker-ios.tar.gz \
            "${{ inputs.upload_url }}"

