on:
  workflow_dispatch: {}

jobs:
  build_worker_tarball:
    name: Build and Upload
    runs_on: macos-medium
    image: latest
    steps:
      - uses: eas/checkout

      - name: Build worker tarball
        run: ./package.sh worker.tar.gz

      - name: Upload worker tarball as artifact
        uses: eas/upload_artifact
        with:
          name: worker-tarball
          path: packages/worker/worker.tar.gz
