import { test, expect } from 'bun:test';

import { filterNoise, matchesIgnore, countChangedLines } from '../core/noise.js';
import type { DiffEntry } from '../core/schema.js';

const entry = (path: string, patch = '@@ -1 +1 @@\n-a\n+b'): DiffEntry => ({
  path,
  patch,
  status: 'M',
  binary: false,
});

test('matchesIgnore: ** crosses dirs, * stays within a segment', () => {
  expect(matchesIgnore('packages/x/build/y.js', 'packages/*/build/**')).toBe(true);
  expect(matchesIgnore('packages/x/src/y.js', 'packages/*/build/**')).toBe(false);
  expect(matchesIgnore('a/b.ts', 'a/*.ts')).toBe(true);
  expect(matchesIgnore('a/b/c.ts', 'a/*.ts')).toBe(false);
});

test('matchesIgnore: regex metacharacters are literal (incl. . and ?)', () => {
  expect(matchesIgnore('a.ts', 'a.ts')).toBe(true);
  expect(matchesIgnore('axts', 'a.ts')).toBe(false); // `.` must be literal
  expect(matchesIgnore('a?b.ts', 'a?b.ts')).toBe(true); // `?` must be literal (the escaping fix)
  expect(matchesIgnore('axb.ts', 'a?b.ts')).toBe(false);
});

test('filterNoise: lockfiles + additionalIgnores globs', async () => {
  const { kept, filtered } = await filterNoise(
    [entry('yarn.lock'), entry('packages/x/build/out.js'), entry('src/keep.ts')],
    { additionalIgnores: ['packages/*/build/**'] },
    '/does/not/exist'
  );
  expect(kept.map(e => e.path)).toEqual(['src/keep.ts']);
  expect(filtered.map(f => f.path).sort()).toEqual(['packages/x/build/out.js', 'yarn.lock']);
});

test('filterNoise: generation marker counts only as a HEADER (self-filter regression)', async () => {
  const header = entry('gen.ts', '@@ -0,0 +1,2 @@\n+// @generated by tool. DO NOT EDIT.\n+export const x = 1;');
  // Marker string appears, but past the header window (7th added line) — a source
  // file that merely mentions the markers, like our own noise.ts.
  const midFile = entry(
    'real.ts',
    '@@ -1,9 +1,9 @@\n+import a;\n+import b;\n+import c;\n+import d;\n+import e;\n+import f;\n+const markers = ["@generated", "do not edit"];'
  );
  const { kept, filtered } = await filterNoise([header, midFile], {}, '/does/not/exist');
  expect(filtered.map(f => f.path)).toEqual(['gen.ts']);
  expect(kept.map(e => e.path)).toEqual(['real.ts']);
});

test('filterNoise: binary entries are filtered with a clear reason', async () => {
  const bin: DiffEntry = { path: 'img.png', patch: 'Binary files differ', status: 'A', binary: true };
  const { kept, filtered } = await filterNoise([bin], {}, '/does/not/exist');
  expect(kept).toEqual([]);
  expect(filtered[0]!.reason).toContain('binary');
});

test('countChangedLines counts + and - lines, excluding +++/--- headers', () => {
  expect(countChangedLines('@@ -1,2 +1,3 @@\n const a=1;\n+const b=2;\n-const c=3;')).toBe(2);
  expect(countChangedLines('--- a/x\n+++ b/x\n@@ -1 +1 @@\n+only-one')).toBe(1);
});
