import { mkdir, open, writeFile } from 'node:fs/promises';
import path from 'node:path';

import type { DiffEntry, ReviewMetadata } from './schema.js';

export interface FilteredFile {
  path: string;
  reason: string;
}

export interface NoiseResult {
  kept: DiffEntry[];
  filtered: FilteredFile[];
}

export interface NoiseOptions {
  /** Extra glob-ish suffixes/paths to always filter, from repo config. */
  additionalIgnores?: string[];
  /** Extra generation markers to detect in added lines, from repo config. */
  additionalMarkers?: string[];
}

const LOCKFILES = new Set(['yarn.lock', 'package-lock.json', 'pnpm-lock.yaml', 'bun.lock']);
const NOISE_EXTENSIONS = ['.min.js', '.min.css', '.bundle.js', '.map'];
const DEFAULT_MARKERS = [
  '@generated',
  '@codegen',
  'code generated by',
  'this file was generated',
  'this file is generated',
  'auto-generated',
  'autogenerated',
  'do not edit',
];

/**
 * Strip files that add no signal (lockfiles, generated bundles/maps, snapshots,
 * generated-file markers, plus any repo-specified extras) before any agent sees
 * them. Reads each file's on-disk head for a generation marker — the diff hunk
 * alone misses markers that live at the top of a file when the change is mid-file.
 */
export async function filterNoise(
  entries: DiffEntry[],
  options: NoiseOptions = {},
  cwd: string = process.cwd()
): Promise<NoiseResult> {
  const kept: DiffEntry[] = [];
  const filtered: FilteredFile[] = [];

  for (const entry of entries) {
    const reason = await noiseReason(entry, options, cwd);
    if (reason) {
      filtered.push({ path: entry.path, reason });
    } else {
      kept.push(entry);
    }
  }

  return { kept, filtered };
}

async function noiseReason(
  entry: DiffEntry,
  options: NoiseOptions,
  cwd: string
): Promise<string | null> {
  if (entry.binary) {
    return 'binary file (no textual diff)';
  }
  const base = path.basename(entry.path);
  if (LOCKFILES.has(base)) {
    return 'lockfile';
  }
  for (const ext of NOISE_EXTENSIONS) {
    if (entry.path.endsWith(ext)) {
      return `generated asset (${ext})`;
    }
  }
  if (entry.path.includes('__snapshots__/') && entry.path.endsWith('.snap')) {
    return 'jest snapshot';
  }
  for (const pattern of options.additionalIgnores ?? []) {
    if (matchesIgnore(entry.path, pattern)) {
      return `repo-ignored (${pattern})`;
    }
  }
  const markers = [...DEFAULT_MARKERS, ...(options.additionalMarkers ?? [])].map(marker =>
    marker.toLowerCase()
  );
  // A generation marker only counts as a HEADER — real generated files carry it
  // in their first few lines (e.g. `// @generated`, `# ... DO NOT EDIT.`). Only
  // checking the top avoids false positives on hand-written files that merely
  // mention these strings (e.g. this module lists them as DEFAULT_MARKERS, and a
  // config comment references "@generated"), which were being wrongly filtered.
  if (hasMarkerHeaderInPatch(entry.patch, markers)) {
    return 'generated file header';
  }
  const head = await readFileHead(path.resolve(cwd, entry.path));
  if (head && hasMarkerInHead(head, markers)) {
    return 'generated file header';
  }
  return null;
}

/** How many leading lines of a file count as its (generation) header. */
const HEADER_LINES = 5;

/** Minimal glob: supports `**` (crosses `/`) and `*` (within a segment). */
export function matchesIgnore(filePath: string, pattern: string): boolean {
  // Translate the glob to a regex in a single pass, escaping metacharacters
  // inline. We deliberately use NO placeholder character: an earlier version
  // stashed a literal NUL byte as a sentinel, which made git classify this
  // source file as binary (so its diff was invisible to reviewers).
  let out = '';
  for (let i = 0; i < pattern.length; i++) {
    const ch = pattern[i]!;
    if (ch === '*') {
      if (pattern[i + 1] === '*') {
        out += '.*';
        i++;
      } else {
        out += '[^/]*';
      }
    } else if (/[.+^${}()|[\]\\?]/.test(ch)) {
      out += '\\' + ch;
    } else {
      out += ch;
    }
  }
  return new RegExp(`^${out}$`).test(filePath);
}

/** A generation marker in the first few ADDED lines (i.e. the top of a new file). */
function hasMarkerHeaderInPatch(patch: string, markers: string[]): boolean {
  const topAddedLines = patch
    .split('\n')
    .filter(line => line.startsWith('+') && !line.startsWith('+++'))
    .slice(0, HEADER_LINES)
    .map(line => line.toLowerCase());
  return topAddedLines.some(line => markers.some(marker => line.includes(marker)));
}

/** A generation marker in the first few lines of the on-disk file. */
function hasMarkerInHead(head: string, markers: string[]): boolean {
  const topLines = head.split('\n').slice(0, HEADER_LINES).join('\n').toLowerCase();
  return markers.some(marker => topLines.includes(marker));
}

/** Read the first `bytes` of a file (default 4 KB) without loading the whole thing. */
async function readFileHead(absPath: string, bytes = 4096): Promise<string | null> {
  try {
    const handle = await open(absPath, 'r');
    try {
      const buffer = Buffer.alloc(bytes);
      const { bytesRead } = await handle.read(buffer, 0, bytes, 0);
      return buffer.subarray(0, bytesRead).toString('utf8');
    } finally {
      await handle.close();
    }
  } catch {
    return null;
  }
}

export interface PatchWorkspaceFile {
  path: string;
  patchPath: string;
  status?: string;
  /** The file's unified-diff patch text (also written to `patchPath` on disk). */
  patch: string;
  /** Added + removed lines in this file's patch (for size-based chunking). */
  changedLines: number;
}

/** Count added + removed lines in a unified-diff patch (ignores +++/--- headers). */
export function countChangedLines(patch: string): number {
  let count = 0;
  for (const line of patch.split('\n')) {
    if (line.startsWith('+') && !line.startsWith('+++')) {
      count++;
    } else if (line.startsWith('-') && !line.startsWith('---')) {
      count++;
    }
  }
  return count;
}

export interface PatchWorkspace {
  root: string;
  manifestPath: string;
  files: PatchWorkspaceFile[];
}

/**
 * Write one patch file per changed file plus a shared manifest, all inside the
 * repo (so the OpenCode read tool can reach them). Agents are pointed at these
 * paths instead of having the full diff inlined into every prompt.
 */
export async function writePatchWorkspace(
  kept: DiffEntry[],
  metadata: ReviewMetadata,
  rootDir: string
): Promise<PatchWorkspace> {
  const patchDir = path.join(rootDir, 'patches');
  await mkdir(patchDir, { recursive: true });

  const files: PatchWorkspaceFile[] = [];
  for (let index = 0; index < kept.length; index++) {
    const entry = kept[index]!;
    const safeName = `${String(index).padStart(4, '0')}-${entry.path.replace(
      /[^a-zA-Z0-9._-]/g,
      '__'
    )}.patch`;
    const patchPath = path.join(patchDir, safeName);
    await writeFile(patchPath, entry.patch, 'utf8');
    files.push({
      path: entry.path,
      patchPath,
      status: entry.status,
      patch: entry.patch,
      changedLines: countChangedLines(entry.patch),
    });
  }

  const manifestPath = path.join(rootDir, 'context.md');
  await writeFile(manifestPath, renderManifest(files, metadata), 'utf8');

  return { root: rootDir, manifestPath, files };
}

function renderManifest(files: PatchWorkspaceFile[], metadata: ReviewMetadata): string {
  const lines: string[] = [
    '# Changed files',
    '',
    `Base: ${metadata.baseRef || '(unknown)'}  Head: ${metadata.headRef || '(unknown)'}`,
    '',
    'Each entry lists the changed file (path relative to repo root) and a patch',
    'file containing its unified diff. Read the patch to see what changed, then',
    'read the surrounding source in the repo to confirm findings in context.',
    '',
  ];
  for (const file of files) {
    lines.push(`- \`${file.path}\` (${file.status ?? 'M'}) — patch: \`${file.patchPath}\``);
  }
  lines.push('');
  return lines.join('\n');
}
