import { type AppiumCommand } from './appiumCommands.generated';

export const APPIUM_COMMAND_SUMMARIES: Record<AppiumCommand, string> = {
  // Session lifecycle
  createSession: 'Started the session',
  deleteSession: 'Ended the session',
  getSession: 'Read the session details',
  getStatus: 'Checked the server status',
  getAppiumSessions: 'Listed Appium sessions',
  getAppiumSessionCapabilities: 'Read the session capabilities',
  getTimeouts: 'Read timeouts',
  timeouts: 'Set timeouts',
  getSettings: 'Read Appium settings',
  updateSettings: 'Updated Appium settings',
  listCommands: 'Listed available commands',
  listExtensions: 'Listed available extensions',
  receiveAsyncResponse: 'Received an async response',

  // Screen and media
  getScreenshot: 'Took a screenshot',
  getElementScreenshot: 'Took a screenshot of an element',
  getPageSource: 'Read the screen contents',
  printPage: 'Printed the page',

  // Window and orientation
  getWindowRect: 'Read the screen size',
  setWindowRect: 'Resized the window',
  maximizeWindow: 'Maximized the window',
  minimizeWindow: 'Minimized the window',
  fullScreenWindow: 'Made the window full screen',
  getWindowHandle: 'Read the current window',
  getWindowHandles: 'Listed open windows',
  setWindow: 'Switched window',
  closeWindow: 'Closed the window',
  createNewWindow: 'Opened a new window',
  setFrame: 'Switched to a frame',
  switchToParentFrame: 'Switched to the parent frame',
  getOrientation: 'Read the screen orientation',
  setOrientation: 'Changed the screen orientation',
  getRotation: 'Read the device rotation',
  setRotation: 'Rotated the device',

  // Device
  getDeviceTime: 'Read the device time',
  getGeoLocation: 'Read the device location',
  setGeoLocation: 'Set the device location',
  getNetworkConnection: 'Read the network connection',
  setNetworkConnection: 'Changed the network connection',
  setDevicePosture: 'Set the device posture',
  clearDevicePosture: 'Cleared the device posture',
  setPermissions: 'Set app permissions',

  // Element discovery
  findElement: 'Found an element',
  findElements: 'Found elements',
  findElementFromElement: 'Found a nested element',
  findElementsFromElement: 'Found nested elements',
  findElementFromShadowRoot: 'Found an element in a shadow root',
  findElementsFromShadowRoot: 'Found elements in a shadow root',
  elementShadowRoot: 'Read an element shadow root',
  active: 'Read the focused element',

  // Element interaction
  click: 'Tapped an element',
  clear: 'Cleared an element',
  setValue: 'Typed into an element',
  getText: 'Read element text',
  getName: 'Read an element tag',
  getAttribute: 'Read an element attribute',
  getProperty: 'Read an element property',
  getCssProperty: 'Read an element style',
  getComputedLabel: 'Read an element label',
  getComputedRole: 'Read an element role',
  getElementRect: 'Read an element position and size',
  elementDisplayed: 'Checked if an element was visible',
  elementEnabled: 'Checked if an element was enabled',
  elementSelected: 'Checked if an element was selected',

  // Gestures
  performActions: 'Performed a gesture',
  releaseActions: 'Finished a gesture',

  // App management
  installApp: 'Installed an app',
  removeApp: 'Removed an app',
  isAppInstalled: 'Checked if an app was installed',
  activateApp: 'Activated an app',
  terminateApp: 'Terminated an app',
  queryAppState: 'Read the app state',
  background: 'Sent the app to the background',

  // Contexts
  getContexts: 'Listed available contexts',
  getCurrentContext: 'Read the current context',
  setContext: 'Switched context',

  // Web navigation
  setUrl: 'Opened a URL',
  getUrl: 'Read the current URL',
  back: 'Navigated back',
  forward: 'Navigated forward',
  refresh: 'Refreshed the page',
  title: 'Read the page title',

  // Cookies
  getCookie: 'Read a cookie',
  getCookies: 'Read all cookies',
  setCookie: 'Set a cookie',
  deleteCookie: 'Deleted a cookie',
  deleteCookies: 'Deleted all cookies',

  // Alerts
  getAlertText: 'Read an alert',
  setAlertText: 'Typed into an alert',
  postAcceptAlert: 'Accepted an alert',
  postDismissAlert: 'Dismissed an alert',

  // Keyboard and input methods
  hideKeyboard: 'Hid the keyboard',
  isKeyboardShown: 'Checked if the keyboard was shown',
  activateIMEEngine: 'Activated an input method',
  deactivateIMEEngine: 'Deactivated the input method',
  getActiveIMEEngine: 'Read the active input method',
  availableIMEEngines: 'Listed input methods',
  isIMEActivated: 'Checked if an input method was active',

  // Clipboard (driver-level, not declared by base-driver)
  getClipboard: 'Read the clipboard',
  setClipboard: 'Wrote to the clipboard',

  // Files
  pushFile: 'Pushed a file to the device',
  pullFile: 'Pulled a file from the device',
  pullFolder: 'Pulled a folder from the device',

  // Logs
  getLog: 'Read device logs',
  getLogTypes: 'Listed log types',
  getLogEvents: 'Read logged events',
  logCustomEvent: 'Logged a custom event',
  generateTestReport: 'Generated a test report',

  // Scripts
  execute: 'Ran a script command',
  executeAsync: 'Ran an async script command',
  executeCdp: 'Ran a Chrome DevTools command',

  // Web authentication (virtual authenticators)
  addVirtualAuthenticator: 'Added a virtual authenticator',
  removeVirtualAuthenticator: 'Removed a virtual authenticator',
  addAuthCredential: 'Added an auth credential',
  getAuthCredential: 'Read auth credentials',
  removeAuthCredential: 'Removed an auth credential',
  removeAllAuthCredentials: 'Removed all auth credentials',
  setUserAuthVerified: 'Set the user verification state',

  // Federated sign-in (FedCM)
  fedCMGetAccounts: 'Listed federated sign-in accounts',
  fedCMSelectAccount: 'Selected a federated sign-in account',
  fedCMGetDialogType: 'Read the federated sign-in dialog type',
  fedCMGetTitle: 'Read the federated sign-in dialog title',
  fedCMClickDialogButton: 'Clicked a federated sign-in dialog button',
  fedCMCancelDialog: 'Canceled the federated sign-in dialog',
  fedCMResetCooldown: 'Reset the federated sign-in cooldown',
  fedCMSetDelayEnabled: 'Toggled the federated sign-in delay',

  // Virtual sensors and pressure sources
  createVirtualSensor: 'Created a virtual sensor',
  updateVirtualSensorReading: 'Updated a virtual sensor reading',
  getVirtualSensorInfo: 'Read virtual sensor info',
  deleteVirtualSensor: 'Removed a virtual sensor',
  createVirtualPressureSource: 'Created a virtual pressure source',
  updateVirtualPressureSource: 'Updated a virtual pressure source',
  deleteVirtualPressureSource: 'Removed a virtual pressure source',

  // Privacy / experimental web platform
  getGlobalPrivacyControl: 'Read the Global Privacy Control setting',
  setGlobalPrivacyControl: 'Set the Global Privacy Control setting',
  setStorageAccess: 'Set storage access',
  setRPHRegistrationMode: 'Set the protocol handler registration mode',
  setSPCTransactionMode: 'Set the payment transaction mode',

  // Driver routes and compatibility commands
  asyncScriptTimeout: 'Set the async script timeout',
  closeApp: 'Closed the app',
  disableConditionInducer: 'Disabled the condition inducer',
  enableConditionInducer: 'Enabled the condition inducer',
  fingerprint: 'Simulated a fingerprint',
  getCurrentActivity: 'Read the current activity',
  getCurrentPackage: 'Read the current package',
  getDisplayDensity: 'Read the display density',
  getLocation: 'Read an element location',
  getLocationInView: 'Read an element location in view',
  getPerformanceData: 'Read performance data',
  getPerformanceDataTypes: 'Listed performance data types',
  getScreenInfo: 'Read screen information',
  getSize: 'Read an element size',
  getStrings: 'Read app strings',
  getSystemBars: 'Read system bar information',
  getViewportRect: 'Read the viewport size',
  getViewportScreenshot: 'Took a viewport screenshot',
  getWindowSize: 'Read the window size',
  gsmCall: 'Simulated a phone call',
  gsmSignal: 'Changed the cellular signal',
  gsmVoice: 'Changed the cellular voice state',
  implicitWait: 'Set the element lookup timeout',
  isLocationServicesEnabled: 'Checked if location services were enabled',
  isLocked: 'Checked if the device was locked',
  keyevent: 'Sent a key event',
  keys: 'Sent keyboard input',
  launchApp: 'Launched the app',
  listConditionInducers: 'Listed condition inducers',
  lock: 'Locked the device',
  longPressKeyCode: 'Long-pressed a key',
  networkSpeed: 'Changed the network speed',
  openNotifications: 'Opened notifications',
  powerAC: 'Changed the charging state',
  powerCapacity: 'Changed the battery level',
  pressKeyCode: 'Pressed a key',
  replaceValue: 'Replaced an element value',
  reset: 'Reset the app',
  sendSMS: 'Simulated a text message',
  sensorSet: 'Changed a sensor value',
  setStylusHandwriting: 'Changed stylus handwriting mode',
  setValueImmediate: 'Typed into an element immediately',
  startActivity: 'Started an activity',
  startAudioRecording: 'Started audio recording',
  startRecordingScreen: 'Started screen recording',
  stopAudioRecording: 'Stopped audio recording',
  stopRecordingScreen: 'Stopped screen recording',
  submit: 'Submitted an element',
  toggleData: 'Toggled mobile data',
  toggleEnrollTouchId: 'Changed Touch ID enrollment',
  toggleFlightMode: 'Toggled airplane mode',
  toggleLocationServices: 'Toggled location services',
  toggleWiFi: 'Toggled Wi-Fi',
  touchId: 'Simulated Touch ID',
  unlock: 'Unlocked the device',

  // Driver mobile commands
  mobileAcceptAlert: 'Accepted an alert',
  mobileActivateApp: 'Activated an app',
  mobileBackgroundApp: 'Sent the app to the background',
  mobileBluetooth: 'Changed Bluetooth state',
  mobileBroadcast: 'Sent an Android broadcast',
  mobileCalibrateWebToRealCoordinatesTranslation: 'Calibrated web coordinates',
  mobileChangePermissions: 'Changed app permissions',
  mobileClearApp: 'Cleared app data',
  mobileClearKeychains: 'Cleared keychains',
  mobileClickGesture: 'Performed a click gesture',
  mobileConfigureLocalization: 'Changed device localization',
  mobileDeepLink: 'Opened a deep link',
  mobileDeleteFile: 'Deleted a device file',
  mobileDeleteFolder: 'Deleted a device folder',
  mobileDeviceidle: 'Changed device idle state',
  mobileDisableVoiceOver: 'Disabled VoiceOver',
  mobileDismissAlert: 'Dismissed an alert',
  mobileDoubleClickGesture: 'Performed a double-click gesture',
  mobileDoubleTap: 'Double-tapped the screen',
  mobileDragFromToForDuration: 'Dragged between screen points',
  mobileDragFromToWithVelocity: 'Dragged with a set velocity',
  mobileDragGesture: 'Performed a drag gesture',
  mobileEnableVoiceOver: 'Enabled VoiceOver',
  mobileEnrollBiometric: 'Changed biometric enrollment',
  mobileExecEmuConsoleCommand: 'Ran an emulator console command',
  mobileExpectNotification: 'Waited for a notification',
  mobileFingerprint: 'Simulated a fingerprint',
  mobileFlingGesture: 'Performed a fling gesture',
  mobileForcePress: 'Force-pressed the screen',
  mobileGetActionHistory: 'Read scheduled action history',
  mobileGetActiveAppInfo: 'Read active app information',
  mobileGetAppearance: 'Read the device appearance',
  mobileGetBatteryInfo: 'Read battery information',
  mobileGetChromeCapabilities: 'Read Chrome capabilities',
  mobileGetConnectivity: 'Read device connectivity',
  mobileGetContentSize: 'Read scrollable content size',
  mobileGetContexts: 'Listed available contexts',
  mobileGetDeviceInfo: 'Read device information',
  mobileGetDeviceTime: 'Read the device time',
  mobileGetGeolocation: 'Read the device location',
  mobileGetIncreaseContrast: 'Read the Increase Contrast setting',
  mobileGetNotifications: 'Read notifications',
  mobileGetPasteboard: 'Read the pasteboard',
  mobileGetPerformanceData: 'Read app performance data',
  mobileGetPermission: 'Read an app permission',
  mobileGetPermissions: 'Read app permissions',
  mobileGetSimulatedLocation: 'Read the simulated location',
  mobileGetSource: 'Read the screen contents',
  mobileGetUiMode: 'Read the Android UI mode',
  mobileGetXctestScreenRecordingInfo: 'Read XCTest screen recording information',
  mobileGsmCall: 'Simulated a phone call',
  mobileGsmSignal: 'Changed the cellular signal',
  mobileGsmVoice: 'Changed the cellular voice state',
  mobileHandleAlert: 'Handled an alert',
  mobileHideKeyboard: 'Hid the keyboard',
  mobileInjectEmulatorCameraImage: 'Injected an emulator camera image',
  mobileInstallApp: 'Installed an app',
  mobileInstallCertificate: 'Installed a certificate',
  mobileInstallMultipleApks: 'Installed multiple APKs',
  mobileInstallXCTestBundle: 'Installed an XCTest bundle',
  mobileIsAppInstalled: 'Checked if an app was installed',
  mobileIsBiometricEnrolled: 'Checked biometric enrollment',
  mobileIsMediaProjectionRecordingRunning: 'Checked media projection recording',
  mobileIsVoiceOverEnabled: 'Checked if VoiceOver was enabled',
  mobileKeys: 'Sent keyboard input',
  mobileKillApp: 'Stopped an app',
  mobileLaunchApp: 'Launched an app',
  mobileListApps: 'Listed installed apps',
  mobileListCertificates: 'Listed certificates',
  mobileListDisplays: 'Listed displays',
  mobileListSms: 'Listed text messages',
  mobileListWindows: 'Listed app windows',
  mobileListXCTestBundles: 'Listed XCTest bundles',
  mobileLongClickGesture: 'Performed a long-click gesture',
  mobileNetworkSpeed: 'Changed the network speed',
  mobileNfc: 'Changed NFC state',
  mobilePerformAccessibilityAudit: 'Ran an accessibility audit',
  mobilePerformEditorAction: 'Performed a keyboard editor action',
  mobilePerformIndigoHidEvent: 'Performed an Indigo HID event',
  mobilePerformIoHidEvent: 'Performed an IOHID event',
  mobilePerformStatusBarCommand: 'Performed a status bar command',
  mobilePinch: 'Pinched the screen',
  mobilePinchCloseGesture: 'Performed a pinch-close gesture',
  mobilePinchOpenGesture: 'Performed a pinch-open gesture',
  mobilePowerAc: 'Changed the charging state',
  mobilePowerCapacity: 'Changed the battery level',
  mobilePressButton: 'Pressed a device button',
  mobilePressKey: 'Pressed a key',
  mobilePullFile: 'Pulled a file from the device',
  mobilePullFolder: 'Pulled a folder from the device',
  mobilePushFile: 'Pushed a file to the device',
  mobilePushNotification: 'Sent a push notification',
  mobileQueryAppState: 'Read the app state',
  mobileRefreshGpsCache: 'Refreshed the GPS cache',
  mobileRemoveApp: 'Removed an app',
  mobileRemoveCertificate: 'Removed a certificate',
  mobileReplaceElementValue: 'Replaced an element value',
  mobileResetAccessibilityCache: 'Reset the accessibility cache',
  mobileResetGeolocation: 'Reset the device location',
  mobileResetLocationService: 'Reset location services',
  mobileResetPermission: 'Reset an app permission',
  mobileResetSimulatedLocation: 'Reset the simulated location',
  mobileRotateElement: 'Rotated an element',
  mobileRunXCTest: 'Ran an XCTest bundle',
  mobileScheduleAction: 'Scheduled a device action',
  mobileScreenshots: 'Took display screenshots',
  mobileScroll: 'Scrolled the screen',
  mobileScrollBackTo: 'Scrolled back to an element',
  mobileScrollGesture: 'Performed a scroll gesture',
  mobileScrollToElement: 'Scrolled to an element',
  mobileSelectPickerWheelValue: 'Changed a picker wheel value',
  mobileSendBiometricMatch: 'Simulated biometric authentication',
  mobileSendMemoryWarning: 'Sent a memory warning',
  mobileSendSms: 'Simulated a text message',
  mobileSendTrimMemory: 'Sent an Android memory trim event',
  mobileSetAppearance: 'Changed the device appearance',
  mobileSetConnectivity: 'Changed device connectivity',
  mobileSetContentSize: 'Changed the content size',
  mobileSetGeolocation: 'Set the device location',
  mobileSetIncreaseContrast: 'Changed the Increase Contrast setting',
  mobileSetPasteboard: 'Wrote to the pasteboard',
  mobileSetPermissions: 'Set app permissions',
  mobileSetSimulatedLocation: 'Set a simulated location',
  mobileSetUiMode: 'Changed the Android UI mode',
  mobileShake: 'Shook the device',
  mobileShell: 'Ran an Android shell command',
  mobileSimctl: 'Ran a simctl command',
  mobileSiriCommand: 'Sent a Siri command',
  mobileStartActivity: 'Started an activity',
  mobileStartLogsBroadcast: 'Started log streaming',
  mobileStartMediaProjectionRecording: 'Started media projection recording',
  mobileStartNetworkMonitor: 'Started network monitoring',
  mobileStartPerfRecord: 'Started performance recording',
  mobileStartScreenRecording: 'Started screen recording',
  mobileStartScreenStreaming: 'Started screen streaming',
  mobileStartService: 'Started a service',
  mobileStartSystemMonitor: 'Started system monitoring',
  mobileStartXctestScreenRecording: 'Started XCTest screen recording',
  mobileStopLogsBroadcast: 'Stopped log streaming',
  mobileStopMediaProjectionRecording: 'Stopped media projection recording',
  mobileStopNetworkMonitor: 'Stopped network monitoring',
  mobileStopPerfRecord: 'Stopped performance recording',
  mobileStopScreenRecording: 'Stopped screen recording',
  mobileStopScreenStreaming: 'Stopped screen streaming',
  mobileStopService: 'Stopped a service',
  mobileStopSystemMonitor: 'Stopped system monitoring',
  mobileStopXctestScreenRecording: 'Stopped XCTest screen recording',
  mobileSwipe: 'Swiped the screen',
  mobileSwipeGesture: 'Performed a swipe gesture',
  mobileTap: 'Tapped the screen',
  mobileTapWithNumberOfTaps: 'Tapped the screen multiple times',
  mobileTerminateApp: 'Terminated an app',
  mobileTouchAndHold: 'Touched and held the screen',
  mobileTwoFingerTap: 'Tapped with two fingers',
  mobileType: 'Typed text',
  mobileUnlock: 'Unlocked the device',
  mobileUnscheduleAction: 'Canceled a scheduled action',
  mobileUpdateSafariPreferences: 'Updated Safari preferences',
  mobileViewPortRect: 'Read the viewport size',
  mobileViewportScreenshot: 'Took a viewport screenshot',
  mobileVoiceOverCurrentSpeech: 'Read current VoiceOver speech',
  mobileVoiceOverMove: 'Moved the VoiceOver cursor',
};

/**
 * Translate a raw Appium command name into a short, human-readable summary.
 *
 * If a command has no curated summary, the raw command name is returned
 * unchanged — we intentionally do not guess a phrasing.
 */
export function humanizeAppiumCommand(command: string): string {
  return (APPIUM_COMMAND_SUMMARIES as Record<string, string>)[command] ?? command;
}
