export const COMMON_FASTLANE_ENV = {
  FASTLANE_DISABLE_COLORS: '1',
  FASTLANE_SKIP_UPDATE_CHECK: '1',
  SKIP_SLOW_FASTLANE_WARNING: 'true',
  FASTLANE_HIDE_TIMESTAMP: 'true',
  LC_ALL: 'en_US.UTF-8',
};
