import { AndroidCredentials, Keystore } from '../android/credentials';
import {
  testKeystore2Base64,
  testKeystoreBase64,
  testPKCS12KeystoreBase64,
  testPKCS12KeystoreEmptyPasswordBase64,
  testPKCS12KeystoreUnencryptedBase64,
} from './fixtures-base64-data';
import { testExperienceName, testJester2ExperienceName } from './fixtures-constants';

export const testKeystore: Keystore = {
  keystore: testKeystoreBase64,
  keystorePassword: 'ae6777e9444a436dbe533d2be46c83ba',
  keyAlias: 'QHdrb3p5cmEvY3JlZGVudGlhbHMtdGVzdA==',
  keyPassword: '43f760fe7ecd4e6a925779eb45bc787b',
};
export const testKeystore2: Keystore = {
  keystore: testKeystore2Base64,
  keystorePassword: '6faeed2326b94effadbeb731510c2378',
  keyAlias: 'QHdrb3p5cmEvY3JlZGVudGlhbHMtdGVzdA==',
  keyPassword: 'e4829b38057042d78f25053f390478f9',
};

// Generated by: keytool -genkey -alias test-alias -keystore keystore.p12 -storetype PKCS12 -keyalg RSA -storepass password -validity 730 -keysize 2048
// A Keystore in a PKCS#12 file, where all entries are under aliases
// This particular PKCS#12 has one key and one certificate under 'test-alias'
export const testPKCS12Keystore: Keystore = {
  keystore: testPKCS12KeystoreBase64,
  keystorePassword: 'password',
  keyAlias: 'test-alias',
};

// openssl req -new -newkey rsa:4096 -nodes -keyout test.key -out test.csr
// openssl x509 -req -sha256 -days 365 -in test.csr -signkey test.key -out test.pem
// openssl pkcs12 -export -in test.pem -inkey test.key -name "test-alias" -passout pass: -out emptyPassword.p12
// cat emptyPassword.p12 | base64
export const testPKCS12EmptyPasswordKeystore: Keystore = {
  keystore: testPKCS12KeystoreEmptyPasswordBase64,
  keystorePassword: '',
  keyAlias: 'test-alias',
};

export const testPushCredentials = {
  fcmApiKey: 'examplefcmapikey',
};

export const testAppCredentials = {
  experienceName: testExperienceName,
  keystore: testKeystore,
  pushCredentials: testPushCredentials,
};

export const testJester2AppCredentials = {
  experienceName: testJester2ExperienceName,
  keystore: testKeystore2,
  pushCredentials: testPushCredentials,
};

export const testAllCredentials: { [key: string]: AndroidCredentials } = {
  [testExperienceName]: testAppCredentials,
};

export function getApiClientWrapperMock() {
  // by default all method throw exceptions to make sure that we only call what is expected
  const getUnexpectedCallMock = () =>
    jest.fn(() => {
      throw new Error('unexpected call');
    });
  return {
    getAllCredentialsApi: getUnexpectedCallMock(),
    getAllCredentialsForAppApi: getUnexpectedCallMock(),
    updateKeystoreApi: getUnexpectedCallMock(),
    updateFcmKeyApi: getUnexpectedCallMock(),
    removeKeystoreApi: getUnexpectedCallMock(),
    removeFcmKeyApi: getUnexpectedCallMock(),
  };
}

export function getAndroidApiMock() {
  return {
    fetchAllAsync: jest.fn(() => testAllCredentials),
    fetchKeystoreAsync: jest.fn(() => testKeystore),
    updateKeystoreAsync: jest.fn(),
    removeKeystoreAsync: jest.fn(),
  };
}

export function getAndroidApiMockWithoutCredentials() {
  return {
    fetchAllAsync: jest.fn(() => []),
    fetchKeystoreAsync: jest.fn(() => null),
    updateKeystoreAsync: jest.fn(),
    removeKeystoreAsync: jest.fn(),
  };
}
