name: setup-mise
description: Install tools via mise

runs:
  using: "composite"
  steps:
    - uses: jdx/mise-action@dad1bfd3df957f44999b559dd69dc1671cb4e9ea # v4.2.1
      with:
        install: true
        cache: true
        experimental: true
