name: setup-mise
description: Install tools via mise

runs:
  using: "composite"
  steps:
    - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1
      with:
        install: true
        cache: true
        experimental: true
