name: setup-mise
description: Install tools via mise

runs:
  using: "composite"
  steps:
    - uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d # v4.2.0
      with:
        install: true
        cache: true
        experimental: true
