import fs from 'fs';
import * as uuid from 'uuid';

export function readEmbeddedManifest(manifestPath: string): { id: string } {
  let parsed: unknown;
  try {
    parsed = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
  } catch {
    throw new Error(
      `Could not read or parse manifest at "${manifestPath}". ` +
        `Check the file exists, is readable, and contains valid JSON.`
    );
  }

  if (
    typeof parsed !== 'object' ||
    parsed === null ||
    typeof (parsed as Record<string, unknown>).id !== 'string'
  ) {
    throw new Error(
      `Manifest at "${manifestPath}" is missing the required "id" field. ` +
        `Make sure you're pointing at the app.manifest generated by expo-updates during your native build, not a different JSON file.`
    );
  }

  const id = (parsed as Record<string, string>).id;
  if (!uuid.validate(id)) {
    throw new Error(
      `Manifest at "${manifestPath}" has an invalid "id" field ("${id}" is not a UUID). ` +
        `Make sure you're pointing at the app.manifest generated by expo-updates during your native build.`
    );
  }

  return { id };
}
