import fs from 'fs';
import * as uuid from 'uuid';

export type EmbeddedManifest = {
  id: string;
};

export function readEmbeddedManifest(manifestPath: string): EmbeddedManifest {
  let raw: string;
  try {
    raw = fs.readFileSync(manifestPath, 'utf8');
  } catch {
    throw new Error(
      `Could not read manifest file at "${manifestPath}". ` +
        `The file exists but could not be read — check that you have permission to access it.`
    );
  }

  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch {
    throw new Error(
      `Manifest file at "${manifestPath}" is not valid JSON. ` +
        `This usually means the file is corrupted or you pointed at the wrong file. ` +
        `Rebuild your app and check that the path points to the app.manifest in your native build output.`
    );
  }

  if (
    typeof parsed !== 'object' ||
    parsed === null ||
    typeof (parsed as Record<string, unknown>).id !== 'string'
  ) {
    throw new Error(
      `Manifest at "${manifestPath}" is missing the required "id" field. ` +
        `Make sure you're pointing at the app.manifest generated by expo-updates during your native build, not a different JSON file.`
    );
  }

  const id = (parsed as Record<string, string>).id;
  if (!uuid.validate(id)) {
    throw new Error(
      `Manifest at "${manifestPath}" has an invalid "id" field ("${id}" is not a UUID). ` +
        `Make sure you're pointing at the app.manifest generated by expo-updates during your native build.`
    );
  }

  return { id };
}
