name: Run installer tests
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run shellcheck and test the installer
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - run: shellcheck bin/install.sh
      - run: bash bin/install.sh
      - run: eas --version
