name: Test scripts

defaults:
  run:
    working-directory: scripts

on:
  push:
    branches: [main]
    paths:
      - 'scripts/**'
  pull_request:
    paths:
      - 'scripts/**'

concurrency:
  group: test-scripts-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup tools
        uses: ./.github/actions/setup-mise
      - run: yarn install --immutable
      - run: yarn typecheck
