name: Test scripts

defaults:
  run:
    working-directory: scripts

on:
  push:
    branches: [main]
    paths:
      - 'scripts/**'
  pull_request:
    paths:
      - 'scripts/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: yarn install --frozen-lockfile --check-files
      - run: yarn typecheck
