on:
  workflow_dispatch:
    inputs:
      dry_run:
        type: boolean
        required: true
        default: true
        description: 'Run the release in dry run mode, without pushing any changes'

name: Manually trigger a release

jobs:
  release:
    name: Trigger a release
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.EXPO_BOT_PAT }}
      INPUT_DRY_RUN: ${{ github.event.inputs.dry_run }}
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          ref: main
          fetch-depth: 0
          token: ${{ secrets.EXPO_BOT_PAT }}
      - uses: ./.github/actions/setup-mise
      - run: |
          # Fetch tags so that `git tag` fails if the new vX.Y.Z tag already exists
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
          # Checkout the main branch
          git checkout main
          git config --global user.email "support+ci@expo.io"
          git config --global user.name "Expo CI"
          yarn install --immutable
          yarn build
          # The changesets in .changeset/ set the version bump.
          yarn release
